### PR TITLE
feat: class support dsmark.

### PR DESCRIPTION
**Pull request by xujunjie-cover**

### CODE REVIEW

**Comment by florianl** [comment]
Hi @xujunjie-cover :wave: 

Thanks for your contribution! Can you provide some insights, why `dsmark` should be added here?
I can't its counterpart in the [Linux kernel](https://github.com/torvalds/linux/tree/master/net/sched) - can you point me to it?

**Comment by xujunjie-cover** [comment]
> Hi @xujunjie-cover 👋
> 
> Thanks for your contribution! Can you provide some insights, why `dsmark` should be added here? I can't identify its counterpart in the [Linux kernel](https://github.com/torvalds/linux/tree/master/net/sched) - can you point me to it?

Sorry, I didn't understand everything before; I want set dscp for egress package from netns.
cli:
```
tc qdisc add dev eth0 parent root handle 10: dsmark indices 8 set_tc_index
tc class change dev eth0 parent 10: classid 10:1 dsmark mask 0x03 value 0x20
```

code:
```
	dsmarkQdisc := tc.Object{
		Msg: tc.Msg{
			Family:  unix.AF_UNSPEC,
			Ifindex: index,
			Handle:  xxx,
			Parent:  root,
			Info:    0,
		},
		Attribute: tc.Attribute{
			Kind: "dsmark",
			Dsmark: &tc.Dsmark{
				Indices:    &indices,
				SetTCIndex: &setTCIndex,
			},
		},
	}
add qdisc

	dsmarkClass := tc.Object{
		Msg: tc.Msg{
			Family:  unix.AF_UNSPEC,
			Ifindex: index,
			Handle:  xxx + 1,
			Parent:  xxx,
			Info:    0,
		},
		Attribute: tc.Attribute{
			Kind: "dsmark",
			Dsmark: &tc.Dsmark{
				Mask:  &mask,
				Value: &value,
			},
		},
	}

replace dsmarkClass
```
before linux 6.2
https://github.com/torvalds/linux/blob/c9c3395d5e3dcc6daee66c6908354d47bf98cb0c/net/sched/sch_dsmark.c#L116

linux 6.3 Retire dsmark qdisc. I think i should close this pr.
https://github.com/torvalds/linux/commit/11b8b2e70a9b4a1b60eefc0cd79cd2d3c08545f1

**Review by florianl — APPROVED** [review]
Sorry for the delayed response! :pray: 

Even if `dsmark` got retired in recent Linux kernels, it is fine for me to support it. When looking this change at first, I didn't look at older Linux kernels and so missed it.

Thanks for your contribution!

Can you please sign the commit, so I can merge it?

**Comment by florianl** [comment]
sorry that I got lost track on this PR and just merge it now. Thanks for your contribution! :pray:

**Pull request merged**
