### PR TITLE
Move helper functions for handles into `core/handle.go`

### PR DESCRIPTION
**Pull request by fbegyn**
The `HandleStr` function prints a TC handle as a human readable handle.
This is done by splitting the handle in it's major and minor part.

### CODE REVIEW

**Comment by florianl** [comment]
`go-tc` focuses on exposing the pure Kernel API. So all the userspace related calculation and representation are not part of it. It's not intended to be a drop in replacement for the original `iproute2/tc`.
For functionality, that is used in multiple classes/qdiscs/filters, the [core](https://github.com/florianl/go-tc/tree/master/core) subpackage has been created. So I see this change more in `core`, than in `go-tc` directly.

**Comment by fbegyn** [comment]
I was not sure if this function indeed belonged in `go-tc` at all, but assumed, since the `BuildHandle` function was present in  `tc.go`, it would be the correct location for it.

So from what I can understand, you see this more in place in `core/handle.go` (for example)? Or would this be something you leave for the user of `go-tc` to implement?

**Comment by florianl** [comment]
yes, `core/handle.go` might be a better place for `HandleStr()` and `BuildHandle()`.

**Comment by florianl** [comment]
hi @fbegyn,
will you update the PR?

**Comment by fbegyn** [comment]
I'm forgetful today, forgot to run some tests locally before pushing :sweat_smile: 

The scope of the commits might be a bit to large for the title of this PR now.

**Pull request merged**
